services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/var/www/html
  oauth2_proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    container_name: ${COMPOSE_PROJECT_NAME}_oauth2_proxy
    ports:
      - 80:4180
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_PROVIDER: github
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_SCOPE: user:email
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_SESSION_STORE_TYPE: redis
      OAUTH2_PROXY_REDIS_CONNECTION_URL: redis://redis/
      OAUTH2_PROXY_UPSTREAMS: "http://nginx"
      # Settings for allow http
      OAUTH2_PROXY_COOKIE_SECURE: 'false'
      OAUTH2_PROXY_REDIRECT_URL: http://localhost/oauth2/callback
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis
    volumes:
      - ./redis/data:/data
